---
title: "Filtering for high confidence lncRNAs"
author: "Antone Jung"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: 
    code_folding: show
    theme: spacelab
    highlight: pygments
    keep_md: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
  keep_md: true  
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center")
```

```{r violin-plots}
install.packages("ggbreak")
devtools::install_github("teunbrand/legendry")
pacman::p_load(tidyverse, dplyr, scales, ggplot2, RColorBrewer, Biostrings, patchwork, ggbreak, tispec, legendry, rtracklayer, install = FALSE)

egg_transcriptome <- readDNAStringSet("resources/eggplant_transcriptome.fasta")
egg_coding_transcriptome <- egg_transcriptome[grepl("g", names(egg_transcriptome), ignore.case = TRUE)]

egg_width <- as.data.frame(width(egg_coding_transcriptome))
colnames(egg_width) <- "value"
egg_width <- egg_width %>% mutate(transcript = "emRNA") %>% mutate(species = "Eggplant")

egg_gc <- as.data.frame(letterFrequency(egg_coding_transcriptome, letters = "GC", as.prob = TRUE))
colnames(egg_gc) <- "value"
egg_gc <- egg_gc %>% mutate(transcript = "emRNA") %>% mutate(species = "Eggplant") %>% mutate(value = value * 100)

egg_lncRNAtome <- readDNAStringSet("data/03_filtering/egg_07lncRNA/egg_lncRNA_genes.fasta")

egg_lncRNA_width <- as.data.frame(width(egg_lncRNAtome))
colnames(egg_lncRNA_width) <- "value"
egg_lncRNA_width <- egg_lncRNA_width %>% mutate(transcript = "elncRNA") %>% mutate(species = "Eggplant")

egg_lncRNA_gc <- as.data.frame(letterFrequency(egg_lncRNAtome, letters = "GC", as.prob = TRUE))
colnames(egg_lncRNA_gc) <- "value"
egg_lncRNA_gc <- egg_lncRNA_gc %>% mutate(transcript = "elncRNA") %>% mutate(species = "Eggplant") %>% mutate(value = value * 100)

egg_quant_lncRNA <- egg_quant %>% filter(grepl("MSTRG", rownames(.)))
egg_lncRNA <- names(egg_lncRNAtome)
egg_quant_lncRNA <- egg_quant_lncRNA %>% filter(rownames(.) %in% egg_lncRNA)
egg_quant_mRNA <- egg_quant %>% filter(grepl("g", rownames(.)))

egg_meta_tau <- data.frame(row.names = colnames(egg_quant)) %>% mutate(organ = 0) %>%
  mutate(organ = ifelse(grepl("\\bF\\d", rownames(egg_meta)), 1, organ)) %>%
  mutate(organ = ifelse(grepl("\\bMF\\d", rownames(egg_meta)), 2, organ)) %>%
  mutate(organ = ifelse(grepl("\\bsb\\d", rownames(egg_meta)), 3, organ)) %>%
  mutate(organ = ifelse(grepl("spine\\d", rownames(egg_meta)), 4, organ)) %>%
  mutate(organ = ifelse(grepl("Firstleaf\\d", rownames(egg_meta)), 5, organ)) %>%
  mutate(organ = ifelse(grepl("root\\d", rownames(egg_meta)), 6, organ)) %>%
  mutate(organ = ifelse(grepl("stem\\d", rownames(egg_meta)), 7, organ)) %>%
  mutate(organ = ifelse(grepl("shoot\\d", rownames(egg_meta)), 8, organ)) %>%
  mutate(organ = ifelse(grepl("SeedlingRoot\\d", rownames(egg_meta)), 9, organ)) %>%
  mutate(organ = ifelse(grepl("\\bUpSeedling|\\bseedling|\\bup", rownames(egg_meta)), 10, organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruit\\b", rownames(egg_meta)), 11, organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruitpeel", rownames(egg_meta)), 12, organ)) %>%
  mutate(organ = ifelse(grepl("bigFruit", rownames(egg_meta)), 13, organ))

egg_tau_lncRNA_preavg <- cbind(t(egg_quant_lncRNA), egg_meta_tau)
egg_tau_lncRNA_preavg <- group_by(egg_tau_lncRNA_preavg, organ)
egg_tau_lncRNA_avg <- egg_tau_lncRNA_preavg %>% summarise(across(where(is.numeric), ~ exp(mean(log(.x), na.rm = TRUE)))) %>% select(-organ) %>% t(.) %>% as.data.frame(.)

egg_lncRNA_tau <- calcTau(egg_tau_lncRNA_avg)
egg_lncRNA_tau <- egg_lncRNA_tau %>% select(tau) %>% dplyr::rename(value = tau) %>% mutate(transcript = "elncRNA") %>% mutate(species = "Eggplant")

egg_tau_mRNA_preavg <- cbind(t(egg_quant_mRNA), egg_meta_tau)
egg_tau_mRNA_preavg <- group_by(egg_tau_mRNA_preavg, organ)
egg_tau_mRNA_avg <- egg_tau_mRNA_preavg %>% summarise(across(where(is.numeric), ~ exp(mean(log(.x), na.rm = TRUE)))) %>% select(-organ) %>% t(.) %>% as.data.frame(.)

egg_mRNA_tau <- calcTau(egg_tau_mRNA_avg)
egg_mRNA_tau <- egg_mRNA_tau %>% select(tau) %>% dplyr::rename(value = tau) %>% mutate(transcript = "emRNA") %>% mutate(species = "Eggplant")

egg_total_width <- rbind(egg_lncRNA_width, egg_width)

egg_total_gc <- rbind(egg_lncRNA_gc, egg_gc)

egg_total_tau <- rbind(egg_lncRNA_tau, egg_mRNA_tau)

GeomSplitViolin <- ggproto("GeomSplitViolin", GeomViolin,
  draw_group = function(self, data, ..., draw_quantiles = NULL) {
    # Original function by Jan Gleixner (@jan-glx)
    # Adjustments by Wouter van der Bijl (@Axeman)
    data <- transform(data, xminv = x - violinwidth * (x - xmin), xmaxv = x + violinwidth * (xmax - x))
    grp <- data[1, "group"]
    newdata <- plyr::arrange(transform(data, x = if (grp %% 2 == 1) xminv else xmaxv), if (grp %% 2 == 1) y else -y)
    newdata <- rbind(newdata[1, ], newdata, newdata[nrow(newdata), ], newdata[1, ])
    newdata[c(1, nrow(newdata) - 1, nrow(newdata)), "x"] <- round(newdata[1, "x"])
    if (length(draw_quantiles) > 0 & !scales::zero_range(range(data$y))) {
      stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 1))
      quantiles <- create_quantile_segment_frame(data, draw_quantiles, split = TRUE, grp = grp)
      aesthetics <- data[rep(1, nrow(quantiles)), setdiff(names(data), c("x", "y")), drop = FALSE]
      aesthetics$alpha <- rep(1, nrow(quantiles))
      both <- cbind(quantiles, aesthetics)
      quantile_grob <- GeomPath$draw_panel(both, ...)
      ggplot2:::ggname("geom_split_violin", grid::grobTree(GeomPolygon$draw_panel(newdata, ...), quantile_grob))
    }
    else {
      ggplot2:::ggname("geom_split_violin", GeomPolygon$draw_panel(newdata, ...))
    }
  }
)

create_quantile_segment_frame <- function(data, draw_quantiles, split = FALSE, grp = NULL) {
  dens <- cumsum(data$density) / sum(data$density)
  ecdf <- stats::approxfun(dens, data$y)
  ys <- ecdf(draw_quantiles)
  violin.xminvs <- (stats::approxfun(data$y, data$xminv))(ys)
  violin.xmaxvs <- (stats::approxfun(data$y, data$xmaxv))(ys)
  violin.xs <- (stats::approxfun(data$y, data$x))(ys)
  if (grp %% 2 == 0) {
    data.frame(
      x = vctrs::vec_interleave(violin.xs, violin.xmaxvs),
      y = rep(ys, each = 2), group = rep(ys, each = 2)
    )
  } else {
    data.frame(
      x = vctrs::vec_interleave(violin.xminvs, violin.xs),
      y = rep(ys, each = 2), group = rep(ys, each = 2)
    )
  }
}

geom_split_violin <- function(mapping = NULL, data = NULL, stat = "ydensity", position = "identity", ..., 
                              draw_quantiles = NULL, trim = TRUE, scale = "area", na.rm = FALSE, 
                              show.legend = NA, inherit.aes = TRUE) {
  layer(data = data, mapping = mapping, stat = stat, geom = GeomSplitViolin, position = position, 
        show.legend = show.legend, inherit.aes = inherit.aes, 
        params = list(trim = trim, scale = scale, draw_quantiles = draw_quantiles, na.rm = na.rm, ...))
}


#TOM
tom_transcriptome <- readDNAStringSet("resources/tomato_transcriptome.fasta")
tom_coding_transcriptome <- tom_transcriptome[grepl("g", names(tom_transcriptome), ignore.case = TRUE)]

tom_width <- as.data.frame(width(tom_coding_transcriptome))
colnames(tom_width) <- "value"
tom_width <- tom_width %>% mutate(transcript = "tmRNA") %>% mutate(species = "Tomato")

tom_gc <- as.data.frame(letterFrequency(tom_coding_transcriptome, letters = "GC", as.prob = TRUE))
colnames(tom_gc) <- "value"
tom_gc <- tom_gc %>% mutate(transcript = "tmRNA") %>% mutate(species = "Tomato") %>% mutate(value = value * 100)

tom_lncRNAtome <- readDNAStringSet("data/03_filtering/tom_07lncRNA/tom_lncRNA_genes.fasta")

tom_lncRNA_width <- as.data.frame(width(tom_lncRNAtome))
colnames(tom_lncRNA_width) <- "value"
tom_lncRNA_width <- tom_lncRNA_width %>% mutate(transcript = "tlncRNA") %>% mutate(species = "Tomato")

tom_lncRNA_gc <- as.data.frame(letterFrequency(tom_lncRNAtome, letters = "GC", as.prob = TRUE))
colnames(tom_lncRNA_gc) <- "value"
tom_lncRNA_gc <- tom_lncRNA_gc %>% mutate(transcript = "tlncRNA") %>% mutate(species = "Tomato") %>% mutate(value = value * 100)

tom_quant_lncRNA <- tom_quant %>% filter(grepl("MSTRG", rownames(.)))
tom_lncRNA <- names(tom_lncRNAtome)
tom_quant_lncRNA <- tom_quant_lncRNA %>% filter(rownames(.) %in% tom_lncRNA)
tom_quant_mRNA <- tom_quant %>% filter(grepl("g", rownames(.)))

tom_meta_tau <- data.frame(row.names = colnames(tom_quant)) %>% mutate(organ = 0) %>%
  mutate(organ = ifelse(grepl("Seedling", rownames(tom_meta)), 1, organ)) %>%
  mutate(organ = ifelse(grepl("Root", rownames(tom_meta)), 2, organ)) %>%
  mutate(organ = ifelse(grepl("Shoot", rownames(tom_meta)), 3, organ)) %>%
  mutate(organ = ifelse(grepl("SAM", rownames(tom_meta)), 4, organ)) %>%
  mutate(organ = ifelse(grepl("AcroStem", rownames(tom_meta)), 5, organ)) %>%
  mutate(organ = ifelse(grepl("BasiStem", rownames(tom_meta)), 6, organ)) %>%
  mutate(organ = ifelse(grepl("Flower", rownames(tom_meta)), 7, organ)) %>%
  mutate(organ = ifelse(grepl("Old", rownames(tom_meta)), 8, organ)) %>%
  mutate(organ = ifelse(grepl("Young", rownames(tom_meta)), 9, organ))

tom_tau_lncRNA_preavg <- cbind(t(tom_quant_lncRNA), tom_meta_tau)
tom_tau_lncRNA_preavg <- group_by(tom_tau_lncRNA_preavg, organ)
tom_tau_lncRNA_avg <- tom_tau_lncRNA_preavg %>% summarise(across(where(is.numeric), ~ exp(mean(log(.x), na.rm = TRUE)))) %>% select(-organ) %>% t(.) %>% as.data.frame(.)

tom_lncRNA_tau <- calcTau(tom_tau_lncRNA_avg)
tom_lncRNA_tau <- tom_lncRNA_tau %>% select(tau) %>% dplyr::rename(value = tau) %>% mutate(transcript = "tlncRNA") %>% mutate(species = "Tomato")

tom_tau_mRNA_preavg <- cbind(t(tom_quant_mRNA), tom_meta_tau)
tom_tau_mRNA_preavg <- group_by(tom_tau_mRNA_preavg, organ)
tom_tau_mRNA_avg <- tom_tau_mRNA_preavg %>% summarise(across(where(is.numeric), ~ exp(mean(log(.x), na.rm = TRUE)))) %>% select(-organ) %>% t(.) %>% as.data.frame(.)

tom_mRNA_tau <- calcTau(tom_tau_mRNA_avg)
tom_mRNA_tau <- tom_mRNA_tau %>% select(tau) %>% dplyr::rename(value = tau) %>% mutate(transcript = "tmRNA") %>% mutate(species = "Tomato")

tom_total_width <- rbind(tom_lncRNA_width, tom_width)

tom_total_gc <- rbind(tom_lncRNA_gc, tom_gc)

tom_total_tau <- rbind(tom_lncRNA_tau, tom_mRNA_tau)
  
#GRAPHING
total_width <- rbind(egg_total_width, tom_total_width)
total_gc <- rbind(egg_total_gc, tom_total_gc)
total_tau <- rbind(egg_total_tau, tom_total_tau)

((ggplot(total_width,
       aes(as.factor(species), value, fill = transcript)) +
  geom_split_violin(draw_quantiles = c(0.25, 0.5, 0.75)) + 
    scale_fill_manual(values = c("#B398F4", "#F3C7F8", "#609C54", "#D3F9CD")) + theme(legend.position = "none", axis.text.x = element_blank(), plot.title = element_text(size = 10)) + scale_y_log10(labels = label_log(base = 10)) + guides(y = guide_axis_logticks()) +
    labs(x = NULL, y = "nucleotides", title = "Transcript Length") +
    coord_cartesian(ylim = c(100, 10000))) + 
  
  (ggplot(total_gc,
       aes(as.factor(species), value, fill = transcript)) +
  geom_split_violin(draw_quantiles = c(0.25, 0.5, 0.75)) + 
    scale_fill_manual(values = c("#B398F4", "#F3C7F8", "#609C54", "#D3F9CD")) + theme(legend.position = "none", axis.text.x = element_blank(), plot.title = element_text(size = 10)) +
    labs(x = NULL, y = "GC percentage (%)", title = "Nucleotide Composition") +
    coord_cartesian(ylim = c(20, 60)) )) /  
  
  (ggplot(total_tau,
       aes(as.factor(species), value, fill = transcript)) +
  geom_split_violin(draw_quantiles = c(0.25, 0.5, 0.75)) + 
    scale_fill_manual(labels = c("", "", "lncRNA", "mRNA"), values = c("#B398F4", "#F3C7F8", "#609C54", "#D3F9CD")) + 
    theme(legend.position = "bottom", plot.title = element_text(size = 10)) +     guides(fill = guide_legend(nrow = 2, ncol = 2, title = NULL)) +
    labs(x = NULL, y = expression(tau~("TAU")~index), title = "Tissue Specificity")) +

  plot_annotation(title = "LncRNA vs mRNA characteristics")

t.test(egg_lncRNA_gc$value, egg_gc$value)
t.test(egg_lncRNA_width$value, egg_width$value)
t.test(egg_lncRNA_tau$value, egg_mRNA_tau$value)

t.test(tom_lncRNA_gc$value, tom_gc$value)
t.test(tom_lncRNA_width$value, tom_width$value)
t.test(tom_lncRNA_tau$value, tom_mRNA_tau$value)
```

```{r exp_heatmaps}
install.packages("gt")
pacman::p_load(tidyverse, patchwork, RColorBrewer, viridis, patchwork, gt, install = FALSE)

egg_lncRNA_long <- egg_quant_lncRNA %>% mutate(across(everything(), ~ log2(.x + 1))) %>% mutate(transcript = rownames(.)) %>% pivot_longer(., cols = !transcript, names_to = "sample", values_to = "expression")

egg_lncRNA_long_meta <- egg_lncRNA_long %>% 
  mutate(organ = 0) %>%
  mutate(organ = ifelse(grepl("\\bF\\d", sample), 1, organ)) %>%
  mutate(organ = ifelse(grepl("\\bMF\\d", sample), 2, organ)) %>%
  mutate(organ = ifelse(grepl("\\bsb\\d", sample), 3, organ)) %>%
  mutate(organ = ifelse(grepl("spine\\d", sample), 4, organ)) %>%
  mutate(organ = ifelse(grepl("Firstleaf\\d", sample), 5, organ)) %>%
  mutate(organ = ifelse(grepl("root\\d", sample), 6, organ)) %>%
  mutate(organ = ifelse(grepl("stem\\d", sample), 7, organ)) %>%
  mutate(organ = ifelse(grepl("shoot\\d", sample), 8, organ)) %>%
  mutate(organ = ifelse(grepl("SeedlingRoot\\d", sample), 9, organ)) %>%
  mutate(organ = ifelse(grepl("\\bUpSeedling|\\bseedling|\\bup", sample), 10, organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruit\\b", sample), 11, organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruitpeel", sample), 12, organ)) %>%
  mutate(organ = ifelse(grepl("bigFruit", sample), 13, organ))

egg_lncRNA_peaks <- egg_lncRNA_long_meta %>% 
  group_by(transcript) %>% 
  slice_max(order_by = expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ) %>% 
  dplyr::rename(peaked_at_sample = sample)

egg_lncRNA_num_peaks_organ <- egg_lncRNA_peaks %>% 
  group_by(peaked_at_organ) %>% 
  count() %>% 
  arrange(-n) %>%
  dplyr::rename(n_organ = n)

egg_lncRNA_num_peaks_sample <- egg_lncRNA_peaks %>% 
  group_by(peaked_at_sample) %>% 
  count() %>% 
  arrange(-n) %>%
  dplyr::rename(n_sample = n)

egg_lncRNA_peaks_reordered <- egg_lncRNA_peaks %>% 
  inner_join(egg_lncRNA_num_peaks_organ, by = "peaked_at_organ") %>% 
  inner_join(egg_lncRNA_num_peaks_sample, by = "peaked_at_sample") %>%
  arrange(-n_organ, -n_sample, expression)

egg_lncRNA_samples_reordered <- egg_lncRNA_num_peaks_sample %>% 
  mutate(peaked_at_organ = 0) %>%
  mutate(peaked_at_organ = ifelse(grepl("\\bF\\d", peaked_at_sample), 1, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("\\bMF\\d", peaked_at_sample), 2, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("\\bsb\\d", peaked_at_sample), 3, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("spine\\d", peaked_at_sample), 4, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Firstleaf\\d", peaked_at_sample), 5, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("root\\d", peaked_at_sample), 6, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("stem\\d", peaked_at_sample), 7, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("shoot\\d", peaked_at_sample), 8, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("SeedlingRoot\\d", peaked_at_sample), 9, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("\\bUpSeedling|\\bseedling|\\bup", peaked_at_sample), 10, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("5cmFruit\\b", peaked_at_sample), 11, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("5cmFruitpeel", peaked_at_sample), 12, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("bigFruit", peaked_at_sample), 13, peaked_at_organ)) %>%
  inner_join(egg_lncRNA_num_peaks_organ, by = "peaked_at_organ") %>% 
  arrange(-n_organ, -n_sample)
  
egg_lncRNA_long_meta$sample <- factor(egg_lncRNA_long_meta$sample, levels = egg_lncRNA_samples_reordered$peaked_at_sample)
egg_lncRNA_long_meta$transcript <- factor(egg_lncRNA_long_meta$transcript, levels = egg_lncRNA_peaks_reordered$transcript)

egg_x_label <- c("", "", "", "1", "", "", "", "", "", "", "2", "", "", "", "", "3", "", "", "4", "", "", "5", "", "", "6", "", "", "", "7", "", "", "8", "", "", "9", "", "", "10", "", "11", "", "", "12", "", "13")

egg_x_key <- data.frame(Number = c("1", "2", "3", "4", "5","6","7","8","9","10","11","12","13"), Tissue = c("SeedlingShoot", "Prickle", "SeedlingRoot", "OpenFlower","BigFruit", "MediumFlowerBud", "SmallFlowerBud", "MatureRoot", "MatureStem", "SmallFruitPeel", "FirstTrueLeaf", "MatureShoot", "SmallFruit"))

egg_reordered_heatmap <- egg_lncRNA_long_meta %>% 
  ggplot(aes(x = sample, y = transcript)) +
  geom_tile(aes(fill = expression)) +
  scale_fill_gradientn(colors = brewer.pal(9, "YlGnBu")) +
  theme(axis.text.y.left = element_blank(),
        axis.ticks.y.left = element_blank(), legend.position = "right",
    legend.justification = "top",
    axis.ticks.x.bottom = element_blank()) +
  scale_x_discrete(labels = egg_x_label) +
  labs(title = "Eggplant LncRNA Expression", y = "LncRNA Transcripts", x = "Tissue Type", fill = expression(paste(log[2], "TPM")))

egg_reordered_heatmap + gt::gt(egg_x_key)

#TOM
tom_lncRNA_long <- tom_quant_lncRNA %>% mutate(across(everything(), ~ log2(.x + 1))) %>% mutate(transcript = rownames(.)) %>% pivot_longer(., cols = !transcript, names_to = "sample", values_to = "expression")

tom_lncRNA_long_meta <- tom_lncRNA_long %>% mutate(organ = 0) %>%
  mutate(organ = ifelse(grepl("Seedling", sample), 1, organ)) %>%
  mutate(organ = ifelse(grepl("Root", sample), 2, organ)) %>%
  mutate(organ = ifelse(grepl("Shoot", sample), 3, organ)) %>%
  mutate(organ = ifelse(grepl("SAM", sample), 4, organ)) %>%
  mutate(organ = ifelse(grepl("AcroStem", sample), 5, organ)) %>%
  mutate(organ = ifelse(grepl("BasiStem", sample), 6, organ)) %>%
  mutate(organ = ifelse(grepl("Flower", sample), 7, organ)) %>%
  mutate(organ = ifelse(grepl("Old", sample), 8, organ)) %>%
  mutate(organ = ifelse(grepl("Young", sample), 9, organ))

tom_lncRNA_peaks <- tom_lncRNA_long_meta %>% 
  group_by(transcript) %>% 
  slice_max(order_by = expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ) %>% 
  dplyr::rename(peaked_at_sample = sample)

tom_lncRNA_num_peaks_organ <- tom_lncRNA_peaks %>% 
  group_by(peaked_at_organ) %>% 
  count() %>% 
  arrange(-n) %>%
  dplyr::rename(n_organ = n)

tom_lncRNA_num_peaks_sample <- tom_lncRNA_peaks %>% 
  group_by(peaked_at_sample) %>% 
  count() %>% 
  arrange(-n) %>%
  dplyr::rename(n_sample = n)

tom_lncRNA_peaks_reordered <- tom_lncRNA_peaks %>% 
  inner_join(tom_lncRNA_num_peaks_organ, by = "peaked_at_organ") %>% 
  inner_join(tom_lncRNA_num_peaks_sample, by = "peaked_at_sample") %>%
  arrange(-n_organ, -n_sample, expression)

tom_lncRNA_samples_reordered <- tom_lncRNA_num_peaks_sample %>% 
  mutate(peaked_at_organ = 0) %>%
  mutate(peaked_at_organ = ifelse(grepl("Seedling", peaked_at_sample), 1, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Root", peaked_at_sample), 2, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Shoot", peaked_at_sample), 3, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("SAM", peaked_at_sample), 4, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("AcroStem", peaked_at_sample), 5, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("BasiStem", peaked_at_sample), 6, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Flower", peaked_at_sample), 7, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Old", peaked_at_sample), 8, peaked_at_organ)) %>%
  mutate(peaked_at_organ = ifelse(grepl("Young", peaked_at_sample), 9, peaked_at_organ)) %>%
  inner_join(tom_lncRNA_num_peaks_organ, by = "peaked_at_organ") %>% 
  arrange(-n_organ, -n_sample)
  
tom_lncRNA_long_meta$sample <- factor(tom_lncRNA_long_meta$sample, levels = tom_lncRNA_samples_reordered$peaked_at_sample)
tom_lncRNA_long_meta$transcript <- factor(tom_lncRNA_long_meta$transcript, levels = tom_lncRNA_peaks_reordered$transcript)

tom_x_label <- c("", "", "1", "", "", "", "2", "", "", "", "3", "", "", "", "", "4", "", "", "", "", "5", "", "", "", "6", "", "", "", "", "7", "", "", "", "", "8", "", "", "", "", "9", "", "")

tom_x_key <- data.frame(Number = c("1", "2", "3", "4", "5","6","7","8","9"), Tissue = c("Flower", "SAM", "Root", "OldLeaves","BasiStem", "Seedling", "Shoot", "YoungLeaves", "AcroStem"))

tom_reordered_heatmap <- tom_lncRNA_long_meta %>% 
  ggplot(aes(x = sample, y = transcript)) +
  geom_tile(aes(fill = expression)) +
  scale_fill_gradientn(colors = brewer.pal(9, "YlGnBu")) +
  theme(axis.text.y.left = element_blank(),
        axis.ticks.y.left = element_blank(), legend.position = "right",
    legend.justification = "top",
    axis.ticks.x.bottom = element_blank()) +
  scale_x_discrete(labels = tom_x_label) +
  labs(title = "Tomato LncRNA Expression", y = "LncRNA Transcripts", x = "Tissue Type", fill = expression(paste(log[2], "TPM")))

tom_reordered_heatmap + gt::gt(tom_x_key)
```

```{r WGCNA}
pacman::p_load(WGCNA, tidyverse, CorLevelPlot, gridExtra, dplyr, RColorBrewer, igraph, install = FALSE)

allowWGCNAThreads()

# Egg ----
# 1. Fetch Data ------------------------------------------------
egg_quant <-  read.csv("data/03_filtering/egg_04quant/egg_quant_matrix.txt", sep = "\t", row.names = 1)
egg_quant <- egg_quant[,1:45]

# 2. QC - outlier detection ------------------------------------------------

egg_gsg <- goodSamplesGenes(t(egg_quant))
table(egg_gsg$goodGenes)
table(egg_gsg$goodSamples)

# remove genes that are detectd as outliers
egg_quant <- egg_quant[egg_gsg$goodGenes == TRUE,]

# pca - method 2

egg_pca <- prcomp(t(egg_quant))
egg_pca.dat <- egg_pca$x

egg_pca.var <- egg_pca$sdev^2
egg_pca.var.percent <- round(egg_pca.var/sum(egg_pca.var)*100, digits = 2)

egg_pca.dat <- as.data.frame(egg_pca.dat)

ggplot(egg_pca.dat, aes(PC1, PC2)) +
  geom_point() +
  geom_text(label = rownames(egg_pca.dat))
  labs(x = paste0('PC1: ', egg_pca.var.percent[1], ' %'),
       y = paste0('PC2: ', egg_pca.var.percent[2], ' %'))

# 3. Log transform ----
egg_quant <- log(egg_quant + 1)

# 4. Network Construction  ---------------------------------------------------
# Choose a set of soft-thresholding powers
power <- c(c(1:10), seq(from = 12, to = 50, by = 2))

# Call the network topology analysis function
egg_sft <- pickSoftThreshold(t(egg_quant),
                  powerVector = power,
                  networkType = "signed",
                  verbose = 5)


egg_sft.data <- egg_sft$fitIndices
egg_soft_power <- 5
cor <- WGCNA::cor
egg_bwnet <- blockwiseModules(t(egg_quant),
                 maxBlockSize = 40000,
                 TOMType = "unsigned",
                 power = egg_soft_power,
                 randomSeed = 10202005,
                 minModuleSize = 50, 
                 reassignThreshold = 0, 
                 mergeCutHeight = 0.2, 
                 deepSplit = 2,
                 saveTOMs = TRUE,
                 saveTOMFileBase = "egg")

# 5. Module Eigengenes ---------------------------------------------------------
egg_module_eigengenes <- egg_bwnet$MEs


# Print out a preview
head(egg_module_eigengenes)


# get number of genes for each module
table(egg_bwnet$colors)

# Adjust merge for appropriate amount of MEs
egg_merged = mergeCloseModules(t(egg_quant), egg_bwnet$colors, egg_module_eigengenes, cutHeight = 0.2)

egg_module_eigengenes <- egg_merged$newMEs

plotDendroAndColors(egg_bwnet$dendrograms[[1]], cbind(egg_bwnet$unmergedColors[egg_bwnet$blockGenes[[1]]], egg_bwnet$colors[egg_bwnet$blockGenes[[1]]]),
                    c("unmerged", "merged"),
                    dendroLabels = FALSE,
                    addGuide = TRUE,
                    hang= 0.03,
                    guideHang = 0.05)

# 6A. Relate modules to tissues --------------------------------------------------

egg_meta <- data.frame(row.names = colnames(egg_quant)) %>%
  mutate(OpenFlower = ifelse(grepl("\\bF\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(MediumFlowerBud = ifelse(grepl("\\bMF\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(SmallFlowerBud = ifelse(grepl("\\bsb\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(Prickle = ifelse(grepl("spine\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(FirstLeaf = ifelse(grepl("Firstleaf\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(MatureRoot = ifelse(grepl("root\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(MatureStem = ifelse(grepl("stem\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(MatureShoot = ifelse(grepl("shoot\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(SeedlingRoot = ifelse(grepl("SeedlingRoot\\d", rownames(egg_meta)), 1, 0)) %>%
  mutate(SeedlingShoot = ifelse(grepl("\\bUpSeedling|\\bseedling|\\bup", rownames(egg_meta)), 1, 0)) %>%
  mutate(SmallFruit = ifelse(grepl("5cmFruit\\b", rownames(egg_meta)), 1, 0)) %>%
  mutate(SmallFruitPeel = ifelse(grepl("5cmFruitpeel", rownames(egg_meta)), 1, 0)) %>%
  mutate(BigFruit = ifelse(grepl("bigFruit", rownames(egg_meta)), 1, 0))


# Define numbers of genes and samples
egg_nSamples <- ncol(egg_quant)
egg_nGenes <- nrow(egg_quant)

# visualize module-trait association as a heatmap

egg_wgcna_heatmap <- merge(egg_module_eigengenes, egg_meta, by = 'row.names')

head(egg_wgcna_heatmap)

egg_wgcna_heatmap <- egg_wgcna_heatmap %>% 
  column_to_rownames(var = 'Row.names')

egg_corvals <- as.data.frame(stats::cor((egg_wgcna_heatmap)[69:81], (egg_wgcna_heatmap)[1:68])) %>% rownames_to_column("col") %>% pivot_longer(2:69, names_to = "row", values_to = "value")

egg_peak_values <- egg_corvals %>%
  group_by(row) %>% 
  slice_max(order_by = value, n = 1, with_ties = F) %>%
  dplyr::rename(peaked_at = col)

egg_number_of_peaks <- egg_peak_values %>% 
  group_by(peaked_at) %>% 
  count() %>% 
  arrange(n)

egg_peak_values_reordered <- egg_peak_values %>% 
  inner_join(egg_number_of_peaks, by = "peaked_at") %>% 
  arrange(n, peaked_at, value)

egg_corvals$col <- factor(egg_corvals$col, levels = unique(egg_peak_values_reordered$peaked_at))
egg_corvals$row <- factor(egg_corvals$row, levels = unique(egg_peak_values_reordered$row))

egg_y_labs <- egg_peak_values_reordered %>% mutate(row = ifelse(value > 0.75, row, "")) %>% arrange(n, value) %>% .$row

egg_reordered_wgcna_heatmap <- egg_corvals %>% 
  ggplot(aes(x = col, y = row)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradientn(limits = c(-1,1), colors = brewer.pal(9, "PuOr")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text.y = element_text(size = 5)) +
  labs(y = "Gene Module", x = "Tissue", title = "Eggplant WGCNA-Tissue Correlation", fill = "Pearson") +
  guides(fill = guide_colorbar(barheight = unit(14, "cm"), display = "gradient")) + scale_y_discrete(labels = egg_y_labs)

egg_reordered_wgcna_heatmap


# 6B. Gene membership ---------------

egg_membership_cor <- cor(egg_module_eigengenes, t(egg_quant), use = 'p')
egg_membership_pvals <- corPvalueStudent(egg_membership_cor, egg_nSamples)
egg_connectivity <- signedKME(t(egg_quant), egg_module_eigengenes)

egg_black_connectivity <- intramodularConnectivity.fromExpr(t(egg_quant), colors = egg_bwnet$colors, power = egg_soft_power, getWholeNetworkConnectivity = FALSE, ignoreColors = unique(egg_bwnet$colors)[unique(egg_bwnet$colors) != "black"], scaleByMax = TRUE)

names(egg_black_connectivity) <- rownames(egg_quant)
egg_black_connectivity <- egg_black_connectivity[!is.na(egg_black_connectivity)]
egg_black_connectivity <- as.data.frame(egg_black_connectivity) %>% arrange(-egg_black_connectivity)

egg_black_lncRNA <- grep("MSTRG", names(which(egg_bwnet$colors == "black")), value = TRUE)
egg_cyan_lncRNA <- grep("MSTRG", names(which(egg_bwnet$colors == "cyan")), value = TRUE)

writeLines(append(egg_black_lncRNA, egg_cyan_lncRNA), "data/04_characterization/egg_01GO/prickle_lncRNAs.txt")

egg_midnightblue_lncRNA <- grep("MSTRG", names(which(egg_bwnet$colors == "midnightblue")), value = TRUE)



# Tomato ----
# 1. Fetch Data ------------------------------------------------
tom_quant <-  read.csv("data/03_filtering/tom_04quant/tom_quant_matrix.txt", sep = "\t", row.names = 1)
tom_quant <- tom_quant[,1:42]

# 2. QC - outlier detection ------------------------------------------------

tom_gsg <- goodSamplesGenes(t(tom_quant))
table(tom_gsg$goodGenes)
table(tom_gsg$goodSamples)

# remove genes that are detectd as outliers
tom_quant <- tom_quant[tom_gsg$goodGenes == TRUE,]

# pca - method 2

tom_pca <- prcomp(t(tom_quant))
tom_pca.dat <- tom_pca$x

tom_pca.var <- tom_pca$sdev^2
tom_pca.var.percent <- round(tom_pca.var/sum(tom_pca.var)*100, digits = 2)

tom_pca.dat <- as.data.frame(tom_pca.dat)

ggplot(tom_pca.dat, aes(PC1, PC2)) +
  geom_point() +
  geom_text(label = rownames(tom_pca.dat)) +
  labs(x = paste0('PC1: ', tom_pca.var.percent[1], ' %'),
       y = paste0('PC2: ', tom_pca.var.percent[2], ' %'))

# 3. Log transform ----
tom_quant <- log(tom_quant + 1)

# 4. Network Construction  ---------------------------------------------------
# Choose a set of soft-thresholding powers
power <- c(c(1:10), seq(from = 12, to = 50, by = 2))

# Call the network topology analysis function
tom_sft <- pickSoftThreshold(t(tom_quant),
                  powerVector = power,
                  networkType = "signed",
                  verbose = 5)


tom_sft.data <- tom_sft$fitIndices
tom_soft_power <- 18
cor <- WGCNA::cor
tom_bwnet <- blockwiseModules(t(tom_quant),
                 maxBlockSize = 40000,
                 TOMType = "unsigned",
                 power = tom_soft_power,
                 randomSeed = 10202005,
                 minModuleSize = 50, 
                 reassignThreshold = 0, 
                 mergeCutHeight = 0.2, 
                 deepSplit = 2,
                 saveTOMFileBase = "tom",
                 saveTOMs = TRUE)

# 5. Module Eigengenes ---------------------------------------------------------
tom_module_eigengenes <- tom_bwnet$MEs


# Print out a preview
head(tom_module_eigengenes)


# get number of genes for each module
table(tom_bwnet$colors)

# Plot the dendrogram and the module colors before and after merging underneath
plotDendroAndColors(tom_bwnet$dendrograms[[1]], cbind(tom_bwnet$unmergedColors[tom_bwnet$blockGenes[[1]]], tom_bwnet$colors[tom_bwnet$blockGenes[[1]]]),
                    c("unmerged", "merged"),
                    dendroLabels = FALSE,
                    addGuide = TRUE,
                    hang= 0.03,
                    guideHang = 0.05)

# 6A. Relate modules to tissues --------------------------------------------------
tom_meta <- data.frame(row.names = colnames(tom_quant))
tom_meta <- tom_meta %>%
  mutate(Seedling = ifelse(grepl("Seedling", rownames(tom_meta)), 1, 0)) %>%
  mutate(Root = ifelse(grepl("Root", rownames(tom_meta)), 1, 0)) %>%
  mutate(Shoot = ifelse(grepl("Shoot", rownames(tom_meta)), 1, 0)) %>%
  mutate(SAM = ifelse(grepl("SAM", rownames(tom_meta)), 1, 0)) %>%
  mutate(AcroStem = ifelse(grepl("AcroStem", rownames(tom_meta)), 1, 0)) %>%
  mutate(BasiStem = ifelse(grepl("BasiStem", rownames(tom_meta)), 1, 0)) %>%
  mutate(Flower = ifelse(grepl("Flower", rownames(tom_meta)), 1, 0)) %>%
  mutate(OldLeaves = ifelse(grepl("Old", rownames(tom_meta)), 1, 0)) %>%
  mutate(YoungLeaves = ifelse(grepl("Young", rownames(tom_meta)), 1, 0))


# Define numbers of genes and samples
tom_nSamples <- ncol(tom_quant)
tom_nGenes <- nrow(tom_quant)

# visualize module-trait association as a heatmap

tom_wgcna_heatmap <- merge(tom_module_eigengenes, tom_meta, by = 'row.names')

head(tom_wgcna_heatmap)

tom_wgcna_heatmap <- tom_wgcna_heatmap %>% 
  column_to_rownames(var = 'Row.names')

tom_corvals <- as.data.frame(stats::cor((tom_wgcna_heatmap)[47:55], (tom_wgcna_heatmap)[1:46])) %>% rownames_to_column("col") %>% pivot_longer(2:47, names_to = "row", values_to = "value")

tom_peak_values <- tom_corvals %>%
  group_by(row) %>% 
  slice_max(order_by = value, n = 1, with_ties = F) %>%
  dplyr::rename(peaked_at = col)

tom_number_of_peaks <- tom_peak_values %>% 
  group_by(peaked_at) %>% 
  count() %>% 
  arrange(n)

tom_peak_values_reordered <- tom_peak_values %>% 
  inner_join(tom_number_of_peaks, by = "peaked_at") %>% 
  arrange(n, peaked_at, value)

tom_corvals$col <- factor(tom_corvals$col, levels = unique(tom_peak_values_reordered$peaked_at))
tom_corvals$row <- factor(tom_corvals$row, levels = unique(tom_peak_values_reordered$row))

tom_y_labs <- tom_peak_values_reordered %>% mutate(row = ifelse(value > 0.75, row, "")) %>% arrange(n, value) %>% .$row

tom_reordered_wgcna_heatmap <- tom_corvals %>% 
  ggplot(aes(x = col, y = row)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradientn(limits = c(-1,1), colors = brewer.pal(9, "PiYG")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text.y = element_text(size = 5)) +
  labs(y = "Gene Module", x = "Tissue", title = "Tomato WGCNA-Tissue Correlation", fill = "Pearson") +
  guides(fill = guide_colorbar(barheight = unit(14, "cm"), display = "gradient")) + scale_y_discrete(labels = tom_y_labs)

tom_reordered_wgcna_heatmap

# 6B. Gene membership ---------------

tom_membership_cor <- cor(tom_module_eigengenes, t(tom_quant), use = 'p')
tom_membership_pvals <- corPvalueStudent(tom_membership_cor, tom_nSamples)
tom_connectivity <- signedKME(t(tom_quant), tom_module_eigengenes)
```

```{bash eggnog_mapper_local}
cd resources
git clone https://github.com/eggnogdb/eggnog-mapper.git
cd eggnog-mapper
python download_eggnog_data.py

python emapper.py -i ../tomato_transcriptome.fasta -m diamond --data_dir data --itype genome --genepred prodigal --dmnd_ignore_warnings --dbmem --translate --go_evidence non-electronic --pfam_realign none --report_orthologs --decorate_gff yes --evalue 0.001 --score 60 --pident 40 --query_cover 20 --subject_cover 20 --tax_scope auto --target_orthologs all -o ../ttotal_eggnog

conda create -n eggnog -c bioconda -c conda-forge eggnog-mapper
conda activate eggnog
emapper.py --data_dir data -m diamond --cpu 24 -i ../tomato_transcriptome.fasta -o ../ttotal_eggnog --evalue 0.001 --score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype CDS --translate --tax_scope auto --target_orthologs all --go_evidence non-electronic --pfam_realign none --report_orthologs --decorate_gff yes --excel --dmnd_ignore_warnings --dmnd_algo ctg --resume --mp_start_method forkserver --temp_dir ../ttotal_eggnog > ../ttotal_eggnog/emapper.out 2> ../ttotal_eggnog/emapper.err
```

```{r GO}
set.seed(10202005)
#if (!requireNamespace("BiocManager", quietly = TRUE)) 
#         install.packages("BiocManager")
#install.packages("data.table")
#BiocManager::install("Rgraphviz")
#BiocManager::install("topGO", force = TRUE)
#install.packages("ggnewscale")
#install.packages("ggtext")

pacman::p_load("dplyr", "tidyverse", "tidyr", "readr", "stringr", "data.table", "topGO", "ggnewscale", "ggtext", install = FALSE)

# read the total transcriptome (universe)
etotal <- fread("resources/etotal_annotations.tsv", sep = "\t")
head(etotal)

egg_go <- as.data.frame(etotal[,c(1,10)])
egg_geneID2GO <- egg_go %>%
  mutate(GO_list = strsplit(GOs, "[,|]")) %>%
  dplyr::select(`#query`, GO_list) %>%
  deframe()

# Make a named factor (1 = DEG, 0 = background)
egg_all_genes <- etotal$`#query`
str(egg_all_genes)


for (color in levels(as.factor(egg_bwnet$colors))){
  geneList <- factor(as.integer(egg_all_genes %in% names(which(egg_bwnet$colors == color))))
  names(geneList) <- egg_all_genes
  
  for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/egg_01GO/", color, "_", annot_type, ".csv"), row.names = FALSE)
}
}

# egg black

geneList <- factor(as.integer(egg_all_genes %in% names(which(egg_bwnet$colors == "black"))))
names(geneList) <- egg_all_genes
egg_black_GOdata <- new("topGOdata",
              ontology = "BP",
              allGenes = geneList,
              geneSelectionFun = fun(x)(x==1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)
egg_black_resultFisher <- runTest(egg_black_GOdata, algorithm = "classic", statistic = "fisher")

egg_black_goResults <- GenTable(egg_black_GOdata,
                      classicFisher = resultFisher,
                      orderBy = "classicFisher",
                      topNodes = 10)

egg_black_goResults <- egg_black_goResults %>% mutate(GeneRatio = Annotated / length(which(egg_bwnet$colors == "black"))) %>% arrange(GeneRatio) %>% arrange(GeneRatio) %>% mutate(classicFisher = log10(as.numeric(classicFisher)))

egg_black_goResults$Term <- factor(egg_black_goResults$Term, levels = unique(egg_black_goResults$Term))

black_bp <- egg_black_goResults %>% 
  ggplot(aes(x = GeneRatio, y = Term, size = Annotated, color = classicFisher)) +
  scale_color_gradientn(colors = rev(brewer.pal(9, "BuPu"))[1:6]) + geom_point() +
  labs(title = "Eggplant MEBlack GO", x = "Gene Ratio", y = "GO Term", size = "Count", color = "p-value")

black_bp

# read the total transcriptome (universe)
ttotal <- fread("resources/ttotal_annotations.csv", sep = ",")
head(ttotal)

tom_go <- as.data.frame(ttotal[,c(1,10)])
tom_geneID2GO <- tom_go %>%
  mutate(GO_list = strsplit(GOs, "[,|]")) %>%
  dplyr::select(`query`, GO_list) %>%
  deframe()

# Make a named factor (1 = DEG, 0 = background)
tom_all_genes <- ttotal$`query`
str(tom_all_genes)


for (color in levels(as.factor(tom_bwnet$colors))){
  geneList <- factor(as.integer(tom_all_genes %in% names(which(tom_bwnet$colors == color))))
  names(geneList) <- tom_all_genes
  
  for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = tom_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      orderBy = "classicFisher",
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/tom_01GO/", color, "_", annot_type, ".csv"), row.names = FALSE)
}
}

#tom green
geneList <- factor(as.integer(tom_all_genes %in% names(which(tom_bwnet$colors == "green"))))
names(geneList) <- tom_all_genes
tom_green_GOdata <- new("topGOdata",
              ontology = "BP",
              allGenes = geneList,
              geneSelectionFun = fun(x)(x==1),
              annot = annFUN.gene2GO,
              gene2GO = tom_geneID2GO)
tom_green_resultFisher <- runTest(tom_green_GOdata, algorithm = "classic", statistic = "fisher")

tom_green_goResults <- GenTable(tom_green_GOdata,
                      classicFisher = resultFisher,
                      orderBy = "classicFisher",
                      topNodes = 10)

tom_green_goResults <- tom_green_goResults %>% mutate(GeneRatio = Annotated / length(which(tom_bwnet$colors == "green"))) %>% arrange(GeneRatio) %>% arrange(GeneRatio) %>% mutate(classicFisher = log10(as.numeric(classicFisher)))

tom_green_goResults$Term <- factor(tom_green_goResults$Term, levels = unique(tom_green_goResults$Term))

tom_green <- tom_green_goResults %>% 
  ggplot(aes(x = GeneRatio, y = Term, size = Annotated, color = classicFisher)) +
  scale_color_gradientn(colors = rev(brewer.pal(9, "BuPu"))[1:6]) + geom_point() +
  labs(title = "Eggplant MEBlack GO", x = "Gene Ratio", y = "GO Term", size = "Count", color = "p-value")

tom_green

go_combined <-
  ggplot(mapping = aes(x = GeneRatio, y = Term, size = Annotated)) + geom_point(data = egg_black_goResults, aes(color = classicFisher), alpha = 0.75) +
  scale_color_gradientn(colors = rev(brewer.pal(9, "BuPu"))[1:6])  + labs(size = "Count", color = "Eggplant <br> log<sub>10</sub>p-value") +
  theme(legend.title = element_markdown()) + new_scale_color() +
 geom_point(data = tom_green_goResults, aes(color = classicFisher), alpha = 0.75) +  scale_color_gradientn(colors = rev(brewer.pal(9, "Greens"))[1:6]) +
  labs(title = "Eggplant MEBlack & Tomato MEGreen", x = "Gene Ratio", y = "GO Term", size = "Count", color = "Tomato <br> log<sub>10</sub>p-value") +
  theme(legend.title = element_markdown(), axis.text.y.left = element_text(size = 12))

go_combined
```

```{bash psMimic}
cd resources/psmimic
./configure make make install
cd test/psRobot_mim 
psRobot_mim -s smRNA -t target
cd ../../../data/04_characterization/egg_02psMimic
psRobot_mim -s ../../../resources/egg_miRNA.fasta -t ../../03_filtering/egg_07lncRNA/egg_lncRNA_genes.fasta

cd ../tom_02psMimic
psRobot_mim -s ../../../resources/tom_miRNA.fasta -t ../../03_filtering/tom_07lncRNA/tom_lncRNA_genes.fasta

```

```{bash orthofinder}
conda create -n orthofinder -c bioconda -c conda-forge orthofinder
conda activate orthofinder
orthofinder -f lncRNAs -M msa -A mafft -d
```

```{r ortholog-analysis}
egg_bwnet$colors[c("MSTRG.13039.1", "MSTRG.25430.1", "MSTRG.25431.1", "MSTRG.14995.1", "MSTRG.25377.1", "MSTRG.37257.1")]
tom_bwnet$colors[c("MSTRG.25850.1", "MSTRG.18334.1", "MSTRG.26470.1", "MSTRG.16802.1", "MSTRG.26436.1", "MSTRG.17898.1")]
```

```{bash genespace}
export PATH=/programs/minimap2-2.30:$PATH

cat data/03_filtering/tom_07lncRNA/tom_lncRNA_genes.fasta resources/tomato_transcriptome.fasta > data/04_characterization/tom_04genespace/tom_cdslnc.fasta

minimap2 -a -x asm5 -t 24 resources/galaxy_m82.fa data/04_characterization/tom_04genespace/tom_cdslnc.fasta > data/04_characterization/tom_04genespace/tom_cdslnc_align.sam

cat data/03_filtering/egg_07lncRNA/egg_lncRNA_genes.fasta resources/eggplant_transcriptome.fasta > data/04_characterization/egg_04genespace/egg_cdslnc.fasta

minimap2 -a -x asm5 -t 24 resources/galaxy_bari06.fa data/04_characterization/egg_04genespace/egg_cdslnc.fasta > data/04_characterization/egg_04genespace/egg_cdslnc_align.sam

export PATH=/programs/bedtools2-2.29.2/bin:$PATH

samtools view -bS data/04_characterization/tom_04genespace/tom_cdslnc_align.sam > data/04_characterization/tom_04genespace/tom_cdslnc_align.bam

samtools view -bS data/04_characterization/egg_04genespace/egg_cdslnc_align.sam > data/04_characterization/egg_04genespace/egg_cdslnc_align.bam

bedtools bamtobed -i data/04_characterization/tom_04genespace/tom_cdslnc_align.bam > data/04_characterization/tom_04genespace/tom_cdslnc_align.bed

bedtools bamtobed -i data/04_characterization/egg_04genespace/egg_cdslnc_align.bam > data/04_characterization/egg_04genespace/egg_cdslnc_align.bed

cd /workdir/$USER
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh

/workdir/aj564/miniconda3

source /programs/miniconda3/bin/activate orthofinder-2.5.4 
cd /home/FrankLab/shared/aj564/eggtom_lncRNA

cp data/04_characterization/tom_04genespace/tom_cdslnc_align.bed data/04_characterization/04genespace_wd/bed/tom.bed

cp data/04_characterization/egg_04genespace/egg_cdslnc_align.bed data/04_characterization/04genespace_wd/bed/egg.bed

awk 'BEGIN{FS=OFS="\t"} {print $1,$2,$3,$4"_"++c[$4],$5,$6}' data/04_characterization/04genespace_wd/bed/tom.bed | cut -f 1-4 > temp.txt
cp temp.txt data/04_characterization/04genespace_wd/bed/tom.bed
rm temp.txt

awk 'BEGIN{FS=OFS="\t"} {print $1,$2,$3,$4"_"++c[$4],$5,$6}' data/04_characterization/04genespace_wd/bed/egg.bed | cut -f 1-4 > temp.txt
cp temp.txt data/04_characterization/04genespace_wd/bed/egg.bed
rm temp.txt

bedtools getfasta -fi resources/galaxy_m82.fa -bed data/04_characterization/04genespace_wd/bed/tom.bed -fo data/04_characterization/04genespace_wd/peptide/tom.fa -nameOnly

bedtools getfasta -fi resources/galaxy_bari06.fa -bed data/04_characterization/04genespace_wd/bed/egg.bed -fo data/04_characterization/04genespace_wd/peptide/egg.fa -nameOnly

grep -Fvf <(cut -f4 data/04_characterization/04genespace_wd/bed/egg.bed) <(grep ">" data/04_characterization/04genespace_wd/peptide/egg.fa | tr -d ">" | awk '{print $1}')

grep -Fvf <(cut -f4 data/04_characterization/04genespace_wd/bed/tom.bed) <(grep ">" data/04_characterization/04genespace_wd/peptide/tom.fa | tr -d ">" | awk '{print $1}')

sed -i 's/:/_/g' data/04_characterization/04genespace_wd/peptide/tom.fa
sed -i 's/:/_/g' data/04_characterization/04genespace_wd/bed/tom.bed
sed -i 's/:/_/g' data/04_characterization/04genespace_wd/peptide/egg.fa
sed -i 's/:/_/g' data/04_characterization/04genespace_wd/bed/egg.bed

orthofinder -f /home/FrankLab/shared/aj564/eggtom_lncRNA/data/04_characterization/04genespace_wd//tmp -t 12 -a 1 -X -o /home/FrankLab/shared/aj564/eggtom_lncRNA/data/04_characterization/04genespace_wd//orthofinder -d



## Using gtf instead of fasta
# peptide should be the same
# use parse annot


cat data/03_filtering/tom_07lncRNA/tom_lncRNA_genes.fasta data/04_characterization/05genespace_wd/rawRepo/tom/tom.fasta > data/04_characterization/05genespace_wd/rawRepo/tom/ttom.fasta

cat data/03_filtering/egg_07lncRNA/egg_lncRNA_genes.fasta data/04_characterization/05genespace_wd/rawRepo/egg/egg.fa > data/04_characterization/05genespace_wd/rawRepo/egg/tegg.fasta

export PATH=/programs/genometools-1.5.9/bin:$PATH

/programs/gffread-0.9.12/gffread/gffread data/03_filtering/tom_07lncRNA/tom_lncRNA_genes.gtf -o- > data/04_characterization/05genespace_wd/rawRepo/tom/lnctom.gff3

/programs/gffread-0.9.12/gffread/gffread data/03_filtering/egg_07lncRNA/egg_lncRNA_genes.gtf -o- > data/04_characterization/05genespace_wd/rawRepo/egg/lncegg.gff3

cat data/04_characterization/05genespace_wd/rawRepo/tom/lnctom.gff3 data/04_characterization/05genespace_wd/rawRepo/tom/cdstom.gff3 > data/04_characterization/05genespace_wd/rawRepo/tom/tom.gff3

cat data/04_characterization/05genespace_wd/rawRepo/egg/lncegg.gff3 data/04_characterization/05genespace_wd/rawRepo/egg/cdsegg.gff3 > data/04_characterization/05genespace_wd/rawRepo/egg/egg.gff3
```

```{r genespace}
devtools::install_github("jtlovell/GENESPACE")
BiocManager::install(c("Biostrings", "rtracklayer"))
pacman::p_load(GENESPACE, Biostrings, rtracklayer, tidyverse, dplyr, ggplot2, cowplot)

parse_annotations(
  rawGenomeRepo = "/home/FrankLab/shared/aj564/eggtom_lncRNA/data/04_characterization/05genespace_wd/rawRepo/",
  genomeDirs = c("tegg", "ttom"),
  genomeIDs = c("tegg", "ttom"),
  gffString = "gff3",
  faString = "fa",
  genespaceWd = "genespace_wd",
  minPepLen = 0,
  dropDuplicates = TRUE,
  removeNonAAs = TRUE,
  presets = "none",
  gffIdColumn = "ID",
  headerEntryIndex = 1,
  headerSep = " ",
  gffStripText = "ID=",
  headerStripText = "",
  convertSpecialCharacters = "_",
  chrIdDictionary = NULL,
  troubleShoot = TRUE,
  overwrite = FALSE
)

path2mcscanx <- "/programs/MCScanX/"
wd <- "/home/FrankLab/shared/aj564/eggtom_lncRNA/data/04_characterization/genespace_wd/"

gpar <- init_genespace(
  wd = wd, 
  path2mcscanx = path2mcscanx, nCores = 24)

out <- run_genespace(gsParam = gpar)
e_genes <- query_pangenes(out, refGenome = "tegg")
t_genes <- query_pangenes(out, refGenome = "ttom")

lncgenes <- e_genes %>% filter(grepl("MSTRG", repGene)) %>% filter(grepl("MSTRG", tegg)) %>% filter(grepl("MSTRG", ttom))

black_prickle_syn <- lncgenes %>% filter(genome == "tegg") %>% filter(repGene %in% egg_black_lncRNA)

cyan_prickle_syn <- lncgenes %>% filter(genome == "tegg") %>% filter(repGene %in% egg_cyan_lncRNA)

black_prickle_syn$ttom %>% unlist()

cyan_prickle_syn$ttom %>% unlist()
  
black_tom_ortho <- data.frame(tom_bwnet$colors) %>% rownames_to_column("name") %>% filter(grepl("MSTRG.3642.1|MSTRG.2324.1|MSTRG.14560.1|MSTRG.14561.1|MSTRG.10412.1|MSTRG.26491.1|MSTRG.29730.1|MSTRG.29820.1|MSTRG.31553.1|MSTRG.31991.1|MSTRG.5270.1|MSTRG.6268.1|MSTRG.17513.1", name))

cyan_tom_ortho <- data.frame(tom_bwnet$colors) %>% rownames_to_column("name") %>% filter(grepl("MSTRG.4335.1|MSTRG.5761.1|MSTRG.18933.1", name))

black_prickle_to_plot <- 
  data.frame(egg = unlist(append(black_prickle_syn$tegg, black_prickle_syn$tegg[[3]], after = 3))) %>%
  mutate(tom = str_subset(str_extract(unlist(black_prickle_syn$ttom), "MSTRG\\.\\d*\\.1"), "MSTRG")) %>%
  inner_join(., black_tom_ortho, by = c("tom" = "name")) %>%
  rename(tom_color = tom_bwnet.colors) %>%
  mutate(tom_color = paste0("ME", tom_color)) %>%
  mutate(egg_color = "MEblack") %>%
  rowwise() %>%
  mutate(egg_cor = egg_membership_cor[egg_color, egg]) %>%
  mutate(egg_p = egg_membership_pvals[egg_color, egg]) %>%
  mutate(tom_cor = tom_membership_cor[tom_color, tom]) %>%
  mutate(tom_p = tom_membership_pvals[tom_color, tom]) %>%
  mutate(tom_color = substring(tom_color, 3))

black_prickle_plot <-
  ggplot(black_prickle_to_plot, aes(x = egg_cor,
                                    y = tom_cor,
                                    color = tom_color,
                                    alpha = ifelse(egg_p < 5e-2 & tom_p < 5e-2, 1, 0.3))) +
  geom_point(size = 4) +
  scale_alpha_identity() +
  scale_color_identity(guide = "legend") + 
  geom_hline(yintercept = 0, color = "black") +
  geom_vline(xintercept = 0, color = "black") +  
  labs(
    title = "Eggplant MEBlack & Tomato Orthologs",
    x = "Eggplant MEBlack Membership",
    y = "Tomato Ortholog Module Membership",
    color = "Tomato Ortholog") + 
  theme(legend.position = "none",
    legend.title = element_text(face = "bold"))

black_prickle_plot + annotate("rect", xmin = 0.45, xmax = 0.95, ymin = 0.7, ymax = 1.05, alpha = 0, color= "#609C54")

cyan_prickle_to_plot <- 
  data.frame(egg = str_subset(str_extract(unlist(cyan_prickle_syn$tegg), "MSTRG\\.\\d*\\.1"), "MSTRG")) %>%
  mutate(tom = append(str_subset(str_extract(unlist(cyan_prickle_syn$ttom), "MSTRG\\.\\d*\\.1"), "MSTRG"), str_subset(str_extract(unlist(cyan_prickle_syn$ttom), "MSTRG\\.\\d*\\.1"), "MSTRG")[2], after = 2)) %>%
  inner_join(., cyan_tom_ortho, by = c("tom" = "name")) %>%
  rename(tom_color = tom_bwnet.colors) %>%
  mutate(tom_color = paste0("ME", tom_color)) %>%
  mutate(egg_color = "MEcyan") %>%
  rowwise() %>%
  mutate(egg_cor = egg_membership_cor[egg_color, egg]) %>%
  mutate(egg_p = egg_membership_pvals[egg_color, egg]) %>%
  mutate(tom_cor = tom_membership_cor[tom_color, tom]) %>%
  mutate(tom_p = tom_membership_pvals[tom_color, tom]) %>%
  mutate(tom_color = substring(tom_color, 3))

cyan_prickle_plot <-
  ggplot(cyan_prickle_to_plot, aes(x = egg_cor,
                                    y = tom_cor,
                                    color = tom_color,
                                    alpha = ifelse(egg_p < 5e-2 & tom_p < 5e-2, 1, 0.3))) +
  geom_point(size = 4) +
  scale_alpha_identity() +
  scale_color_identity(guide = "legend") + 
  geom_hline(yintercept = 0, color = "black") +
  geom_vline(xintercept = 0, color = "black") +  
  labs(
    title = "Eggplant MECyan lncRNAs + Tomato Orthologs",
    x = "Eggplant MECyan Membership",
    y = "Tomato Ortholog Module Membership",
    color = "Tomato Ortholog Module Color") + 
  theme(legend.position = "right",
    legend.title = element_text(face = "bold"))

cyan_prickle_plot  
```

```{r seq_analysis}
pacman::p_load(tidyverse, cowplot)

black_orthos_of_interest <- black_prickle_to_plot %>% filter(grepl("MSTRG.12327.1|MSTRG.20439.1|MSTRG.33641.1|MSTRG.4918.1|MSTRG.31543.1", egg))

egg_orthos_of_interest <- "MSTRG.12327.1|MSTRG.20439.1|MSTRG.33641.1|MSTRG.4918.1|MSTRG.31543.1|MSTRG.24717.1"
tom_orthos_of_interest <- "MSTRG.3642.1|MSTRG.14560.1|MSTRG.14561.1|MSTRG.10412.1|MSTRG.31991.1|MSTRG.5270.1"
```

```{bash fasim-target}
unzip resources/Fasim-LongTarget-main.zip -d resources

cd resources/Fasim-LongTarget-main/

g++ Fasim-LongTarget.cpp ssw_cpp.cpp sswNew.cpp -O -msse2 -o fasim
cd ../../..

cp resources/galaxy_bari06.fa /workdir/aj564
/programs/seqkit-2.13.0/seqkit split --by-id /workdir/aj564/galaxy_bari06.fa

cp data/04_characterization/egg_06fasim/egg_of_interest.fasta /workdir/aj564
/programs/seqkit-2.13.0/seqkit split --by-id /workdir/aj564/egg_of_interest.fasta

cp resources/Fasim-LongTarget-main/fasim /workdir/aj564/

mv /workdir/aj564/egg_of_interest.fasta.split/* /workdir/aj564/
mv /workdir/aj564/galaxy_bari06.fa.split/* /workdir/aj564/

egg_fasim () {
  base=$(basename "$1" .fa)
  /workdir/aj564/fasim -f1 $1 -f2 $2
}
export -f egg_fasim

cd /workdir/aj564/

parallel egg_fasim ::: galaxy_bari06.part_ch07.fa ::: egg_of_interest.part_MSTRG.20439.1.fasta

for file in *TFO*; do [ -f "$file" ] && mv -v -- "$file" "${file:1}"; done
```

```{bash proximal-mRNAs}
grep -E "MSTRG.12327.1|MSTRG.20439.1|MSTRG.33641.1|MSTRG.4918.1|MSTRG.31543.1" data/03_filtering/egg_07lncRNA/egg_lncRNA_genes.gtf > data/04_characterization/egg_07proximal/egg_lncRNA_interest.gtf

bedtools intersect -wao -a data/04_characterization/egg_07proximal/egg_lncRNA_interest.gtf -b resources/eggplant_transcriptome.gtf > data/04_characterization/egg_07proimal/egg_overlaps.txt

grep -E "MSTRG.3642.1|MSTRG.14560.1|MSTRG.14561.1|MSTRG.10412.1|MSTRG.31991.1|MSTRG.5270.1" data/03_filtering/tom_07lncRNA/tom_lncRNA_genes.gtf > data/04_characterization/tom_07proximal/tom_lncRNA_interest.gtf

bedtools intersect -wao -a data/04_characterization/tom_07proximal/tom_lncRNA_interest.gtf -b resources/tomato_transcriptome.gtf > data/04_characterization/tom_07proximal/tom_overlaps.txt
```

```{r proximal-mRNAs}
pacman::p_load(tidyverse)

egg_proximal_genes <- as.data.frame(t(as.data.frame(strsplit(readLines("data/04_characterization/egg_07proximal/egg_overlaps.txt"), split = "\t"))), row.names = FALSE) %>% filter(V12 == "gene") %>% select(V1, V9, V4, V5, V7, V18, V13, V14, V16) %>% mutate(V4 = as.numeric(V4) + 10000) %>% mutate(V5 = as.numeric(V5) - 10000) %>% mutate(V9 = strsplit(V9, split = "\"")) %>% mutate(V9 = sapply(.$V9, function(x) grep("MSTRG", x, value = TRUE)[1])) %>% dplyr::rename(chr = V1, lncRNA = V9, lnc_start = V4, lnc_end = V5, lnc_strand = V7, mRNA = V18, m_start = V13, m_end = V14, m_strand = V16) %>% mutate(lnc_start = as.numeric(lnc_start)) %>% mutate(lnc_end = as.numeric(lnc_end)) %>% mutate(m_start = as.numeric(m_start)) %>% mutate(m_end = as.numeric(m_end))

egg_proximal_genes_annotated <- egg_proximal_genes %>% mutate(distance = ifelse((abs(m_start - lnc_end) < abs(lnc_start - m_end)), m_start - lnc_end, m_end - lnc_start)) %>% rowwise() %>% mutate(exp_cor = cor(as.vector(egg_quant[lncRNA, ]), as.vector(egg_quant[mRNA, ]))[1]) %>% mutate(lnc_color = "black") %>% mutate(m_color = egg_bwnet$colors[mRNA]) %>% mutate(lnc_MM = egg_membership_cor[paste0("ME", lnc_color), lncRNA]) %>% mutate(m_MM = egg_membership_cor[paste0("ME", m_color), mRNA]) %>% inner_join(., egg_go, by = c("mRNA" = "#query"))

geneList <- factor(as.integer(egg_all_genes %in% egg_proximal_genes_annotated$mRNA))
names(geneList) <- egg_all_genes
  
for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/egg_07proximal/", annot_type, ".csv"), row.names = FALSE)
}

tom_proximal_genes <- as.data.frame(t(as.data.frame(strsplit(readLines("data/04_characterization/tom_07proximal/tom_overlaps.txt"), split = "\t"))), row.names = FALSE) %>% 
  filter(V12 == "exon") %>% 
  select(V1, V9, V4, V5, V7, V18, V13, V14, V16) %>% 
  mutate(V4 = as.numeric(V4) + 10000) %>% 
  mutate(V5 = as.numeric(V5) - 10000) %>% 
  mutate(V9 = strsplit(V9, split = "\"")) %>% 
  mutate(V9 = sapply(.$V9, function(x) grep("MSTRG", x, value = TRUE)[1])) %>%
  dplyr::rename(chr = V1, lncRNA = V9, lnc_start = V4, lnc_end = V5, lnc_strand = V7, mRNA = V18, m_start = V13, m_end = V14, m_strand = V16) %>% 
  mutate(lnc_start = as.numeric(lnc_start)) %>% 
  mutate(lnc_end = as.numeric(lnc_end)) %>% 
  mutate(m_start = as.numeric(m_start)) %>% 
  mutate(m_end = as.numeric(m_end)) %>% mutate(mRNA = sapply(strsplit(mRNA, split = "\""), function(x) grep("mRNA", x, value = TRUE)[1]))

tom_proximal_merged <- tom_proximal_genes %>% group_by(mRNA) %>%
  mutate(m_end = max(m_end, na.rm = TRUE)) %>% 
  mutate(m_start = min(m_start, na.rm = TRUE)) %>%
  distinct()

tom_proximal_genes_annotated <- tom_proximal_merged %>% mutate(distance = ifelse((abs(m_start - lnc_end) < abs(lnc_start - m_end)), m_start - lnc_end, m_end - lnc_start)) %>% rowwise() %>% mutate(exp_cor = cor(as.vector(tom_quant[lncRNA, ]), as.vector(tom_quant[mRNA, ]))[1]) %>% mutate(lnc_color = tom_bwnet$colors[lncRNA]) %>% mutate(m_color = tom_bwnet$colors[mRNA]) %>% mutate(lnc_MM = tom_membership_cor[paste0("ME", lnc_color), lncRNA]) %>% mutate(m_MM = tom_membership_cor[paste0("ME", m_color), mRNA]) %>% left_join(., tom_go, by = c("mRNA" = "query"))


geneList <- factor(as.integer(tom_all_genes %in% tom_proximal_genes_annotated$mRNA))
names(geneList) <- tom_all_genes
  
for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = tom_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/tom_07proximal/", annot_type, ".csv"), row.names = FALSE)
}
```

```{bash upstream-binding}
grep "start_codon" resources/eggplant_transcriptome.gtf | awk 'BEGIN {FS=OFS="\t"} !/^#/ {$4 = $4 - 1000} 1' > resources/eggplant_prom_region.gtf
```

```{r upstream-binding}
pacman::p_load(dplyr, readr, janitor, topGO)

egg_prom <- read.delim("resources/eggplant_prom_region.gtf", header = FALSE) %>% filter(V1 != "ch00") %>% dplyr::rename(prom_chr = V1, prom_start = V4, prom_end = V5)

egg_4918_TFO <- strsplit(iconv(read_lines("data/04_characterization/egg_06fasim/MSTRG.4918.1-galaxy_bari06.part_ch01-TFOsorted"), from = "UTF-8", to = "UTF-8", sub = "byte"), split = "\t") 

for (i in 1:length(egg_4918_TFO)){
  if (length(egg_4918_TFO[[i]]) != 19){
    egg_4918_TFO[[i]] <- c(egg_4918_TFO[[i]], character(19 - length(egg_4918_TFO[[i]])))
  }
}

egg_4918_TFO <- data.frame(do.call(rbind, egg_4918_TFO))

egg_4918_TFO <- egg_4918_TFO %>% janitor::row_to_names(row = 1)

egg_4918_TFO <- egg_4918_TFO %>% mutate(Chr = "ch01")

for (i in 2:12) {
  temp <- strsplit(iconv(read_lines(sprintf("data/04_characterization/egg_06fasim/MSTRG.4918.1-galaxy_bari06.part_ch%02d-TFOsorted", i)), from = "UTF-8", to = "UTF-8", sub = "byte"), split = "\t")

  for (j in 1:length(temp)){
    length(temp[[j]]) <- 19
  }
  
  for (j in 1:length(temp)){
    if (length(temp[[j]]) != 19){
      print(as.character(j))
    }
  }

  temp <- data.frame(do.call(rbind, temp))

  temp <- temp %>% janitor::row_to_names(row = 1)

  temp <- temp %>% mutate(Chr = sprintf("ch%02d", i))
  
  egg_4918_TFO <- rbind(egg_4918_TFO, temp)
}

egg_4918_TFO_clean <- egg_4918_TFO %>% filter(!is.na(QueryStart)) %>% mutate(StartInGenome = as.numeric(StartInGenome)) %>% mutate(EndInGenome = as.numeric(EndInGenome))

egg_4918_TFO_prom <- rbind(inner_join(egg_prom, egg_4918_TFO_clean, by = join_by(prom_chr == Chr, prom_start <= StartInGenome, prom_end >= StartInGenome)), inner_join(egg_prom, egg_4918_TFO_clean, by = join_by(prom_chr == Chr, prom_start <= EndInGenome, prom_start >= StartInGenome))) %>% distinct()

egg_4918_TFO_prom_clean <- egg_4918_TFO_prom %>% mutate(V9 = strsplit(V9, split = ";| ")) %>% mutate(V9 = sapply(.$V9, function(x) grep("g", x, value = TRUE)[1]))

egg_4918_genes <- egg_4918_TFO_prom_clean %>% mutate(Score = as.numeric(Score)) %>% filter(Score >= 150)

geneList <- factor(as.integer(egg_all_genes %in% egg_4918_genes))
names(geneList) <- egg_all_genes
  
for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/egg_06fasim/egg_4918_GO/", annot_type, ".csv"), row.names = FALSE)
}


#20439 needs ch01 and ch07

egg_20439_TFO <- strsplit(iconv(read_lines("data/04_characterization/egg_06fasim/MSTRG.20439.1-galaxy_bari06.part_ch02-TFOsorted"), from = "UTF-8", to = "UTF-8", sub = "byte"), split = "\t")

for (i in 1:length(egg_20439_TFO)){
  length(egg_20439_TFO[[i]]) <- 19
}

egg_20439_TFO <- data.frame(do.call(rbind, egg_20439_TFO))

egg_20439_TFO <- egg_20439_TFO %>% janitor::row_to_names(row = 1)

egg_20439_TFO <- egg_20439_TFO %>% mutate(Chr = "ch02")

for (i in 3:12) {
  temp <- strsplit(iconv(read_lines(sprintf("data/04_characterization/egg_06fasim/MSTRG.20439.1-galaxy_bari06.part_ch%02d-TFOsorted", i)), from = "UTF-8", to = "UTF-8", sub = "byte"), split = "\t")

  for (j in 1:length(temp)){
    length(temp[[j]]) <- 19
  }

  temp <- data.frame(do.call(rbind, temp))

  temp <- temp %>% janitor::row_to_names(row = 1)

  temp <- temp %>% mutate(Chr = sprintf("ch%02d", i))
  
  egg_20439_TFO <- rbind(egg_20439_TFO, temp)
}

egg_20439_TFO_clean <- egg_20439_TFO %>% filter(!is.na(QueryStart)) %>% mutate(StartInGenome = as.numeric(StartInGenome)) %>% mutate(EndInGenome = as.numeric(EndInGenome))

egg_20439_TFO_prom <- rbind(inner_join(egg_prom, egg_20439_TFO_clean, by = join_by(prom_chr == Chr, prom_start <= StartInGenome, prom_end >= StartInGenome)), inner_join(egg_prom, egg_20439_TFO_clean, by = join_by(prom_chr == Chr, prom_start <= EndInGenome, prom_start >= StartInGenome))) %>% distinct()

egg_20439_TFO_prom_clean <- egg_20439_TFO_prom %>% mutate(V9 = strsplit(V9, split = ";| ")) %>% mutate(V9 = sapply(.$V9, function(x) grep("g", x, value = TRUE)[1]))

egg_20439_genes <- egg_20439_TFO_prom_clean %>% mutate(`Nt(bp)` = as.numeric(`Nt(bp)`)) %>% filter(`Nt(bp)` >= 100) %>% .$V9 %>% unique()

geneList <- factor(as.integer(egg_all_genes %in% egg_20439_genes))
names(geneList) <- egg_all_genes
  
for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/egg_06fasim/egg_20439_GO/", annot_type, ".csv"), row.names = FALSE)
}

egg_combined_genes <- egg_20439_genes[egg_20439_genes %in% egg_4918_genes]

geneList <- factor(as.integer(egg_all_genes %in% egg_combined_genes))
names(geneList) <- egg_all_genes
  
for (annot_type in c("BP", "CC", "MF")){
# === CREATE topGO OBJECT ===
  GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

# ==="topGO"# === RUN FISHER TEST ===
resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

# === OUTPUT RESULTS ===
goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

print(goResults)
write.csv(goResults, file = paste0("data/04_characterization/egg_06fasim/", annot_type, ".csv"), row.names = FALSE)
}

egg_combined_genes[egg_combined_genes %in% names(which(egg_bwnet$colors == "black"))]
```

```{r checks}
pacman::p_load(dplyr, ggplot2, tidyverse, RColorBrewer)

egg_ortho_vs_all <- cor(t(egg_quant)[,c("MSTRG.12327.1","MSTRG.20439.1","MSTRG.33641.1","MSTRG.4918.1","MSTRG.31543.1","MSTRG.24717.1")], t(egg_quant))

egg_ortho_atlas <- egg_quant[c("MSTRG.12327.1","MSTRG.20439.1","MSTRG.33641.1","MSTRG.4918.1","MSTRG.31543.1","MSTRG.24717.1"),]

egg_ortho_vs_black <- as.data.frame(egg_ortho_vs_all[,names(which(egg_bwnet$colors == "black"))]) %>% tibble::rownames_to_column()

egg_ortho_vs_black <- egg_ortho_vs_black %>% tidyr::pivot_longer(cols = colnames(egg_ortho_vs_black)[-1], names_to = "transcript") %>% group_by(rowname) %>% arrange(-value)

egg_4918_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.4918.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

egg_12327_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.12327.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

egg_20439_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.20439.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

egg_33641_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.33641.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

egg_31543_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.31543.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

egg_24717_high_cor <- egg_ortho_vs_black %>% filter(rowname == "MSTRG.24717.1") %>% filter (value > 0.75) %>% filter(grepl("g", transcript))

for (transcript in c("4918", "12327", "20439", "33641", "31543", "24717")){
  geneList <- factor(as.integer(egg_all_genes %in% get(paste0("egg_", transcript, "_high_cor"))$transcript))
  names(geneList) <- egg_all_genes
  for (annot_type in c("BP", "CC", "MF")){
    GOdata <- new("topGOdata",
              ontology = annot_type,  # Can be "BP", "MF", or "CC"
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.gene2GO,
              gene2GO = egg_geneID2GO)

    resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

    goResults <- GenTable(GOdata,
                      classicFisher = resultFisher,
                      topNodes = 20)

    print(goResults)
    
    write.csv(goResults, file = paste0("data/04_characterization/egg_08neighbors/", transcript, "/", annot_type, ".csv"), row.names = FALSE)
  }
}

egg_interest_quant <- egg_quant[c("MSTRG.12327.1","MSTRG.20439.1","MSTRG.33641.1","MSTRG.4918.1","MSTRG.31543.1","MSTRG.24717.1"),] %>% mutate(across(everything(), ~ log2(.x + 1))) %>% mutate(transcript = rownames(.)) %>% pivot_longer(., cols = !transcript, names_to = "sample", values_to = "expression") %>% 
  mutate(organ = "") %>%
  mutate(organ = ifelse(grepl("\\bF\\d", sample), "Flower", organ)) %>%
  mutate(organ = ifelse(grepl("\\bMF\\d", sample), "MidFlower", organ)) %>%
  mutate(organ = ifelse(grepl("\\bsb\\d", sample), "SmallFlower", organ)) %>%
  mutate(organ = ifelse(grepl("spine\\d", sample), "Prickle", organ)) %>%
  mutate(organ = ifelse(grepl("Firstleaf\\d", sample), "FirstLeaf", organ)) %>%
  mutate(organ = ifelse(grepl("root\\d", sample), "Root", organ)) %>%
  mutate(organ = ifelse(grepl("stem\\d", sample), "Stem", organ)) %>%
  mutate(organ = ifelse(grepl("shoot\\d", sample), "Shoot", organ)) %>%
  mutate(organ = ifelse(grepl("SeedlingRoot\\d", sample), "SeedlingRoot", organ)) %>%
  mutate(organ = ifelse(grepl("\\bUpSeedling|\\bseedling|\\bup", sample), "SeedlingShoot", organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruit\\b", sample), "Fruit", organ)) %>%
  mutate(organ = ifelse(grepl("5cmFruitpeel", sample), "Peel", organ)) %>%
  mutate(organ = ifelse(grepl("bigFruit", sample), "BigFruit", organ)) %>%
  group_by(organ, transcript) %>%
  mutate(avg_expression = mean(expression))

egg_interest_peaks <- egg_interest_quant %>% 
  group_by(transcript) %>% 
  slice_max(order_by = avg_expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ)

egg_interest_organ_peaks <- egg_interest_quant %>% 
  group_by(organ) %>% 
  slice_max(order_by = avg_expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ) %>% arrange(avg_expression)

egg_interest_num_peaks <- egg_interest_peaks %>% 
  group_by(peaked_at_organ) %>% 
  count() %>% 
  arrange(-n)

egg_interest_peaks_reordered <- egg_interest_peaks %>% 
  inner_join(egg_interest_num_peaks, by = "peaked_at_organ") %>%
  arrange(-n, avg_expression)

egg_interest_quant$organ <- factor(egg_interest_quant$organ, levels = egg_interest_organ_peaks$peaked_at_organ)
egg_interest_quant$transcript <- factor(egg_interest_quant$transcript, levels = egg_interest_peaks_reordered$transcript)

egg_interest_heatmap <- egg_interest_quant %>%
  ggplot(aes(x = organ, y = transcript)) +
  geom_tile(aes(fill = avg_expression)) +
  scale_fill_gradientn(colors = brewer.pal(9, "YlGnBu")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

egg_interest_heatmap

tom_interest_quant <- tom_quant[c("MSTRG.3642.1", "MSTRG.14560.1", "MSTRG.14561.1", "MSTRG.10412.1", "MSTRG.31991.1","MSTRG.5270.1"),] %>% mutate(across(everything(), ~ log2(.x + 1))) %>% mutate(transcript = rownames(.)) %>% pivot_longer(., cols = !transcript, names_to = "sample", values_to = "expression") %>% mutate(organ = "") %>%
  mutate(organ = ifelse(grepl("Seedling", sample), "Seedling", organ)) %>%
  mutate(organ = ifelse(grepl("Root", sample), "Root", organ)) %>%
  mutate(organ = ifelse(grepl("Shoot", sample), "Shoot", organ)) %>%
  mutate(organ = ifelse(grepl("SAM", sample), "SAM", organ)) %>%
  mutate(organ = ifelse(grepl("AcroStem", sample), "AcroStem", organ)) %>%
  mutate(organ = ifelse(grepl("BasiStem", sample), "BasiStem", organ)) %>%
  mutate(organ = ifelse(grepl("Flower", sample), "Flower", organ)) %>%
  mutate(organ = ifelse(grepl("Old", sample), "Old", organ)) %>%
  mutate(organ = ifelse(grepl("Young", sample), "Young", organ)) %>%
  group_by(organ, transcript) %>%
  mutate(avg_expression = mean(expression))

tom_interest_peaks <- tom_interest_quant %>% 
  group_by(transcript) %>% 
  slice_max(order_by = avg_expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ)

tom_interest_organ_peaks <- tom_interest_quant %>% 
  group_by(organ) %>% 
  slice_max(order_by = avg_expression, n = 1, with_ties = F) %>% 
  dplyr::rename(peaked_at_organ = organ) %>% arrange(avg_expression)

tom_interest_num_peaks <- tom_interest_peaks %>% 
  group_by(peaked_at_organ) %>% 
  count() %>% 
  arrange(-n)

tom_interest_peaks_reordered <- tom_interest_peaks %>% 
  inner_join(tom_interest_num_peaks, by = "peaked_at_organ") %>%
  arrange(-n, avg_expression)

tom_interest_quant$organ <- factor(tom_interest_quant$organ, levels = tom_interest_organ_peaks$peaked_at_organ)
tom_interest_quant$transcript <- factor(tom_interest_quant$transcript, levels = tom_interest_peaks_reordered$transcript)

tom_interest_heatmap <- tom_interest_quant %>%
  ggplot(aes(x = organ, y = transcript)) +
  geom_tile(aes(fill = avg_expression)) +
  scale_fill_gradientn(colors = brewer.pal(9, "YlGnBu")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

tom_interest_heatmap
```

```{bash alignments}
export PATH=/programs/ncbi-blast-2.16.0+/bin:$PATH

makeblastdb -in data/04_characterization/egg_06fasim/egg_of_interest.fasta -parse_seqids -dbtype nucl -out resources/egg.db -title "Eggplant lncRNAs of Interest Database"

makeblastdb -in data/04_characterization/tom_06fasim/tom_of_interest.fasta -parse_seqids -dbtype nucl -out resources/tom.db -title "Tomato lncRNAs of Interest Database"

blastn -query data/04_characterization/egg_06fasim/egg_of_interest.fasta -db resources/tom.db -out data/04_characterization/egg_06fasim/egg_vs_tom.out

blastn -query data/04_characterization/tom_06fasim/tom_of_interest.fasta -db resources/egg.db -out data/04_characterization/tom_06fasim/tom_vs_egg.out
```

```{r egg-subnetworks}
pacman::p_load(WGCNA, tidyverse, CorLevelPlot, gridExtra, dplyr, RColorBrewer, igraph, install = FALSE)


inBlack <- as.matrix(TOM)[(egg_bwnet$colors == "black"), (egg_bwnet$colors == "black")]

dimnames(inBlack) <- list(names(egg_bwnet$colors)[(egg_bwnet$colors == "black")], names(egg_bwnet$colors)[(egg_bwnet$colors == "black")])

inBlack <- 1/inBlack

inBlack_leiden <- 1/inBlack

inBlack_leiden_graph <- graph_from_adjacency_matrix(
  inBlack_leiden,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

inBlack_clusters <- cluster_leiden(inBlack_leiden_graph, objective_function = "CPM", weights = NULL, resolution = 0.023)
print(inBlack_clusters)

inBlack_graph <- graph_from_adjacency_matrix(
  inBlack,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

subgraph_4918 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.4918.1", weights = NULL)[1, ]))[1:20])
subgraph_4918["MSTRG.4918.1"]
subgraph_4918_filtered <- delete_edges(subgraph_4918, E(subgraph_4918)[weight > max(subgraph_4918["MSTRG.4918.1"])])
plot(subgraph_4918_filtered, layout = layout_nicely)
subgraph_4918_mat <- 1/(as.matrix(subgraph_4918_filtered, attr = "weight"))
subgraph_4918_mat[is.infinite(subgraph_4918_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_4918_mat, edgeFile = "data/04_characterization/egg_08neighbors/4918/4918_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/4918/4918_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_4918_mat))
subgraph_4918_GO <- data.frame(name = names(subgraph_4918["MSTRG.4918.1"]), distance = unname(subgraph_4918["MSTRG.4918.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_24717 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.24717.1", weights = NULL)[1, ]))[1:20])
subgraph_24717["MSTRG.24717.1"]
subgraph_24717_filtered <- delete_edges(subgraph_24717, E(subgraph_24717)[weight > max(subgraph_24717["MSTRG.24717.1"])])
plot(subgraph_24717_filtered, layout = layout_nicely)
subgraph_24717_mat <- 1/(as.matrix(subgraph_24717_filtered, attr = "weight"))
subgraph_24717_mat[is.infinite(subgraph_24717_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_24717_mat, edgeFile = "data/04_characterization/egg_08neighbors/24717/24717_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/24717/24717_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_24717_mat))
subgraph_24717_GO <- data.frame(name = names(subgraph_24717["MSTRG.24717.1"]), distance = unname(subgraph_24717["MSTRG.24717.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_12327 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.12327.1", weights = NULL)[1, ]))[1:20])
subgraph_12327["MSTRG.12327.1"]
subgraph_12327_filtered <- delete_edges(subgraph_12327, E(subgraph_12327)[weight > max(subgraph_12327["MSTRG.12327.1"])])
plot(subgraph_12327_filtered, layout = layout_nicely)
subgraph_12327_mat <- 1/(as.matrix(subgraph_12327_filtered, attr = "weight"))
subgraph_12327_mat[is.infinite(subgraph_12327_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_12327_mat, edgeFile = "data/04_characterization/egg_08neighbors/12327/12327_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/12327/12327_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_12327_mat))
subgraph_12327_GO <- data.frame(name = names(subgraph_12327["MSTRG.12327.1"]), distance = unname(subgraph_12327["MSTRG.12327.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_20439 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.20439.1", weights = NULL)[1, ]))[1:20])
subgraph_20439["MSTRG.20439.1"]
subgraph_20439_filtered <- delete_edges(subgraph_20439, E(subgraph_20439)[weight > max(subgraph_20439["MSTRG.20439.1"])])
plot(subgraph_20439_filtered, layout = layout_nicely)
subgraph_20439_mat <- 1/(as.matrix(subgraph_20439_filtered, attr = "weight"))
subgraph_20439_mat[is.infinite(subgraph_20439_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_20439_mat, edgeFile = "data/04_characterization/egg_08neighbors/20439/20439_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/20439/20439_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_20439_mat))
subgraph_20439_GO <- data.frame(name = names(subgraph_20439["MSTRG.20439.1"]), distance = unname(subgraph_20439["MSTRG.20439.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)


subgraph_33641 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.33641.1", weights = NULL)[1, ]))[1:20])
subgraph_33641["MSTRG.33641.1"]
subgraph_33641_filtered <- delete_edges(subgraph_33641, E(subgraph_33641)[weight > max(subgraph_33641["MSTRG.33641.1"])])
plot(subgraph_33641_filtered, layout = layout_nicely)
subgraph_33641_mat <- 1/(as.matrix(subgraph_33641_filtered, attr = "weight"))
subgraph_33641_mat[is.infinite(subgraph_33641_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_33641_mat, edgeFile = "data/04_characterization/egg_08neighbors/33641/33641_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/33641/33641_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_33641_mat))
subgraph_33641_GO <- data.frame(name = names(subgraph_33641["MSTRG.33641.1"]), distance = unname(subgraph_33641["MSTRG.33641.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_31543 <- induced_subgraph(inBlack_graph, vids = names(sort(distances(inBlack_graph, v = "MSTRG.31543.1", weights = NULL)[1, ]))[1:20])
subgraph_31543["MSTRG.31543.1"]
subgraph_31543_filtered <- delete_edges(subgraph_31543, E(subgraph_31543)[weight > max(subgraph_31543["MSTRG.31543.1"])])
plot(subgraph_31543_filtered, layout = layout_nicely)
subgraph_31543_mat <- 1/(as.matrix(subgraph_31543_filtered, attr = "weight"))
subgraph_31543_mat[is.infinite(subgraph_31543_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_31543_mat, edgeFile = "data/04_characterization/egg_08neighbors/31543/31543_edges.txt", nodeFile = "data/04_characterization/egg_08neighbors/31543/31543_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_31543_mat))
subgraph_31543_GO <- data.frame(name = names(subgraph_31543["MSTRG.31543.1"]), distance = unname(subgraph_31543["MSTRG.31543.1"])) %>% inner_join(etotal, by = c("name" = "#query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)
```

```{r tom-subnetworks}
pacman::p_load(WGCNA, tidyverse, CorLevelPlot, gridExtra, dplyr, RColorBrewer, igraph, install = FALSE)

inTurqoise <- as.matrix(TOM)[(tom_bwnet$colors == "turquoise"), (tom_bwnet$colors == "turquoise")]
dimnames(inTurqoise) <- list(names(tom_bwnet$colors)[(tom_bwnet$colors == "turquoise")], names(tom_bwnet$colors)[(tom_bwnet$colors == "turquoise")])
inTurqoise <- 1/inTurqoise
turq_graph <- graph_from_adjacency_matrix(
  inTurqoise,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

inBlue <- as.matrix(TOM)[(tom_bwnet$colors == "blue"), (tom_bwnet$colors == "blue")]
dimnames(inBlue) <- list(names(tom_bwnet$colors)[(tom_bwnet$colors == "blue")], names(tom_bwnet$colors)[(tom_bwnet$colors == "blue")])
inBlue <- 1/inBlue
blue_graph <- graph_from_adjacency_matrix(
  inBlue,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

inGreen <- as.matrix(TOM)[(tom_bwnet$colors == "green"), (tom_bwnet$colors == "green")]
dimnames(inGreen) <- list(names(tom_bwnet$colors)[(tom_bwnet$colors == "green")], names(tom_bwnet$colors)[(tom_bwnet$colors == "green")])
inGreen <- 1/inGreen
green_graph <- graph_from_adjacency_matrix(
  inGreen,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

inGrey <- as.matrix(TOM)[(tom_bwnet$colors == "grey"), (tom_bwnet$colors == "grey")]
dimnames(inGrey) <- list(names(tom_bwnet$colors)[(tom_bwnet$colors == "grey")], names(tom_bwnet$colors)[(tom_bwnet$colors == "grey")])
inGrey <- 1/inGrey
grey_graph <- graph_from_adjacency_matrix(
  inGrey,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)

subgraph_3642 <- induced_subgraph(turq_graph, vids = names(sort(distances(turq_graph, v = "MSTRG.3642.1", weights = NULL)[1, ]))[1:20])
subgraph_3642["MSTRG.3642.1"]
subgraph_3642_filtered <- delete_edges(subgraph_3642, E(subgraph_3642)[weight > max(subgraph_3642["MSTRG.3642.1"])])
plot(subgraph_3642_filtered, layout = layout_nicely)
subgraph_3642_mat <- 1/(as.matrix(subgraph_3642_filtered, attr = "weight"))
subgraph_3642_mat[is.infinite(subgraph_3642_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_3642_mat, edgeFile = "data/04_characterization/tom_08neighbors/3642/3642_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/3642/3642_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_3642_mat))
subgraph_3642_GO <- data.frame(name = names(subgraph_3642["MSTRG.3642.1"]), distance = unname(subgraph_3642["MSTRG.3642.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_14561 <- induced_subgraph(blue_graph, vids = names(sort(distances(blue_graph, v = "MSTRG.14561.1", weights = NULL)[1, ]))[1:20])
subgraph_14561["MSTRG.14561.1"]
subgraph_14561_filtered <- delete_edges(subgraph_14561, E(subgraph_14561)[weight > max(subgraph_14561["MSTRG.14561.1"])])
plot(subgraph_14561_filtered, layout = layout_nicely)
subgraph_14561_mat <- 1/(as.matrix(subgraph_14561_filtered, attr = "weight"))
subgraph_14561_mat[is.infinite(subgraph_14561_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_14561_mat, edgeFile = "data/04_characterization/tom_08neighbors/14561/14561_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/14561/14561_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_14561_mat))
subgraph_14561_GO <- data.frame(name = names(subgraph_14561["MSTRG.14561.1"]), distance = unname(subgraph_14561["MSTRG.14561.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_5270 <- induced_subgraph(green_graph, vids = names(sort(distances(green_graph, v = "MSTRG.5270.1", weights = NULL)[1, ]))[1:20])
subgraph_5270["MSTRG.5270.1"]
subgraph_5270_filtered <- delete_edges(subgraph_5270, E(subgraph_5270)[weight > max(subgraph_5270["MSTRG.5270.1"])])
plot(subgraph_5270_filtered, layout = layout_nicely)
subgraph_5270_mat <- 1/(as.matrix(subgraph_5270_filtered, attr = "weight"))
subgraph_5270_mat[is.infinite(subgraph_5270_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_5270_mat, edgeFile = "data/04_characterization/tom_08neighbors/5270/5270_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/5270/5270_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_5270_mat))
subgraph_5270_GO <- data.frame(name = names(subgraph_5270["MSTRG.5270.1"]), distance = unname(subgraph_5270["MSTRG.5270.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_10412 <- induced_subgraph(green_graph, vids = names(sort(distances(green_graph, v = "MSTRG.10412.1", weights = NULL)[1, ]))[1:20])
subgraph_10412["MSTRG.10412.1"]
subgraph_10412_filtered <- delete_edges(subgraph_10412, E(subgraph_10412)[weight > max(subgraph_10412["MSTRG.10412.1"])])
plot(subgraph_10412_filtered, layout = layout_nicely)
subgraph_10412_mat <- 1/(as.matrix(subgraph_10412_filtered, attr = "weight"))
subgraph_10412_mat[is.infinite(subgraph_10412_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_10412_mat, edgeFile = "data/04_characterization/tom_08neighbors/10412/10412_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/10412/10412_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_10412_mat))
subgraph_10412_GO <- data.frame(name = names(subgraph_10412["MSTRG.10412.1"]), distance = unname(subgraph_10412["MSTRG.10412.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_31991 <- induced_subgraph(grey_graph, vids = names(sort(distances(grey_graph, v = "MSTRG.31991.1", weights = NULL)[1, ]))[1:20])
subgraph_31991["MSTRG.31991.1"]
subgraph_31991_filtered <- delete_edges(subgraph_31991, E(subgraph_31991)[weight > max(subgraph_31991["MSTRG.31991.1"])])
plot(subgraph_31991_filtered, layout = layout_nicely)
subgraph_31991_mat <- 1/(as.matrix(subgraph_31991_filtered, attr = "weight"))
subgraph_31991_mat[is.infinite(subgraph_31991_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_31991_mat, edgeFile = "data/04_characterization/tom_08neighbors/31991/31991_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/31991/31991_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_31991_mat))
subgraph_31991_GO <- data.frame(name = names(subgraph_31991["MSTRG.31991.1"]), distance = unname(subgraph_31991["MSTRG.31991.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)

subgraph_14560 <- induced_subgraph(grey_graph, vids = names(sort(distances(grey_graph, v = "MSTRG.14560.1", weights = NULL)[1, ]))[1:20])
subgraph_14560["MSTRG.14560.1"]
subgraph_14560_filtered <- delete_edges(subgraph_14560, E(subgraph_14560)[weight > max(subgraph_14560["MSTRG.14560.1"])])
plot(subgraph_14560_filtered, layout = layout_nicely)
subgraph_14560_mat <- 1/(as.matrix(subgraph_14560_filtered, attr = "weight"))
subgraph_14560_mat[is.infinite(subgraph_14560_mat)] <- 0
exportNetworkToCytoscape(adjMat = subgraph_14560_mat, edgeFile = "data/04_characterization/tom_08neighbors/14560/14560_edges.txt", nodeFile = "data/04_characterization/tom_08neighbors/14560/14560_nodes.txt", threshold = 0, nodeNames = rownames(subgraph_14560_mat))
subgraph_14560_GO <- data.frame(name = names(subgraph_14560["MSTRG.14560.1"]), distance = unname(subgraph_14560["MSTRG.14560.1"])) %>% inner_join(ttotal, by = c("name" = "query")) %>% select(c("name","distance", "score", "Description", "PFAMs", "Preferred_name")) %>% arrange(distance)
```

